// {
//     "current_page": 1,
//     "data": [
//         {
//             "id": 1,
//             "first_name": "Administrator",
//             "last_name": null,
//             "email": "admin@yourstore.com",
//             "phone": "03073338359",
//             "dob": "12/21/2017",
//             "address": "FB Area",
//             "country": "Pakistan",
//             "city": "Karachi",
//             "postal": "75300",
//             "shipping_meta": {
//                 "country": "Pakistan",
//                 "city": "Karachi",
//                 "postal": "75300",
//                 "address": "FB Area"
//             },
//             "billing_meta": {
//                 "first_name": "My Friend",
//                 "last_name": "Close",
//                 "country": "Pakistan",
//                 "city": "Islamabad",
//                 "postal": "9632",
//                 "phone": "0387464884",
//                 "address": "TD AREA"
//             },
//             "user_type": "admin",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": null,
//             "updated_at": "2024-05-02 15:18:53",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 2,
//             "first_name": "Webnet",
//             "last_name": "Pakistan",
//             "email": "admin@webnet.com.pk",
//             "phone": "03073338359",
//             "dob": "",
//             "address": "b-69 Block 18",
//             "country": "Pakistan",
//             "city": "Karachi",
//             "postal": "75300",
//             "shipping_meta": {
//                 "country": "Pakistan",
//                 "city": "Karachi",
//                 "postal": "75300",
//                 "address": "b-69 Block 18"
//             },
//             "billing_meta": null,
//             "user_type": "webnet",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": null,
//             "updated_at": "2021-10-02 22:25:31",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 257,
//             "first_name": "webnet",
//             "last_name": "admin",
//             "email": "admin@yourstore.com",
//             "phone": "75676777",
//             "dob": "11/13/2020",
//             "address": "Karachi",
//             "country": "Pakistan",
//             "city": "Karachi",
//             "postal": "75500",
//             "shipping_meta": {
//                 "country": "Pakistan",
//                 "city": "Karachi",
//                 "postal": "75500",
//                 "address": "Karachi"
//             },
//             "billing_meta": null,
//             "user_type": "admin",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2020-11-13 10:50:15",
//             "updated_at": "2021-03-22 18:22:42",
//             "secret": "12345678",
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 313,
//             "first_name": "Test",
//             "last_name": "Test",
//             "email": "suleman@webnet.com.pk",
//             "phone": "03072181860",
//             "dob": null,
//             "address": "Testting",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75500",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-04-08 09:53:22",
//             "updated_at": "2021-04-08 09:53:22",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 314,
//             "first_name": "Test",
//             "last_name": "Test",
//             "email": "Qurban@webnet.com.pk",
//             "phone": "00000000000",
//             "dob": null,
//             "address": "Testing",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "00000",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-04-28 19:19:29",
//             "updated_at": "2021-04-28 19:19:29",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 315,
//             "first_name": "Sidra",
//             "last_name": null,
//             "email": "marketing@taazagosht.pk",
//             "phone": "+92 336 2479358",
//             "dob": null,
//             "address": "block 18, B/69, Gulshan-e-Iqbal",
//             "country": "Pakistan",
//             "city": "Karachi",
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "admin",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-04-30 23:35:56",
//             "updated_at": "2021-06-10 18:23:38",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 316,
//             "first_name": "Waqas",
//             "last_name": "Badshah",
//             "email": "info@webnet.com.pk",
//             "phone": "03008239166",
//             "dob": null,
//             "address": "b-69 Block 18, Gulshan-e-Iqbal",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75300",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-05-01 00:32:21",
//             "updated_at": "2021-05-01 00:32:21",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 317,
//             "first_name": "abdul rehman",
//             "last_name": "shah",
//             "email": "abdul.rehman@webnet.com.pk",
//             "phone": "03073338359",
//             "dob": null,
//             "address": "testing",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "76400",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-05-04 22:49:38",
//             "updated_at": "2021-05-04 22:49:38",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 318,
//             "first_name": "'bilal",
//             "last_name": "qweqwe",
//             "email": "bilal@webnet.com.pk",
//             "phone": null,
//             "dob": null,
//             "address": null,
//             "country": null,
//             "city": null,
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-06-22 19:36:29",
//             "updated_at": "2021-06-22 19:36:29",
//             "secret": "123456",
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 319,
//             "first_name": "Mrs Ilyas",
//             "last_name": "Ilyas",
//             "email": "mariam.shaikh58@gmail.com",
//             "phone": "03212403874",
//             "dob": null,
//             "address": "84- khayaban e Shaheen, phase-6,DHA,karachi",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75500",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-07-12 16:48:15",
//             "updated_at": "2021-07-12 17:11:16",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 320,
//             "first_name": "Ali",
//             "last_name": "Rizvi",
//             "email": "contactaameer@gmail.com",
//             "phone": "03342944892",
//             "dob": null,
//             "address": "Saima Square 1, E1203 Dalmia Ro",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-07-20 18:10:58",
//             "updated_at": "2021-07-20 18:10:58",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 321,
//             "first_name": "Sana",
//             "last_name": "Zahid",
//             "email": "sanazahid153@gmail.com",
//             "phone": "03358272271",
//             "dob": null,
//             "address": "D 136 Dhaka house block 5 fb Area",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "750700",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-07-20 19:17:59",
//             "updated_at": "2021-07-20 19:17:59",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 322,
//             "first_name": "Abdul",
//             "last_name": "Jalil",
//             "email": "jalil.hijazy@gmail.com",
//             "phone": "03178039955",
//             "dob": null,
//             "address": "DHA phase 7. Khayabane ittehad road behind zubaidas shop. upper queta shandar cafe 2nd floor",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-07-27 01:10:46",
//             "updated_at": "2021-07-27 01:10:46",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 323,
//             "first_name": "Asghar",
//             "last_name": "Ali",
//             "email": "bearto775@gmail.com",
//             "phone": null,
//             "dob": null,
//             "address": null,
//             "country": null,
//             "city": null,
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-07-30 12:31:18",
//             "updated_at": "2021-07-30 12:31:32",
//             "secret": "789789qq",
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 324,
//             "first_name": "Haris",
//             "last_name": "Ali",
//             "email": "syed.ali@webnet.com.pk",
//             "phone": null,
//             "dob": null,
//             "address": null,
//             "country": null,
//             "city": null,
//             "postal": null,
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 1,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-08-10 20:46:12",
//             "updated_at": "2021-08-10 20:46:41",
//             "secret": "123456",
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 325,
//             "first_name": "Adeel",
//             "last_name": "Ahmed",
//             "email": "johnadil78@gmail.com",
//             "phone": "03013312967",
//             "dob": null,
//             "address": "A/624 gulshan iqbal block 3. Karachi",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75300",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-08-15 18:12:40",
//             "updated_at": "2021-08-15 18:12:40",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 326,
//             "first_name": "Aamir",
//             "last_name": "Aleem",
//             "email": "emailawami1@gmail.com",
//             "phone": "03323715472",
//             "dob": null,
//             "address": "Flat A3 southern cooperative society next to Jinnah lawn behind capri cinema",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75400",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-08-23 15:07:26",
//             "updated_at": "2021-08-23 15:43:02",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 327,
//             "first_name": "Hina",
//             "last_name": "Khurram",
//             "email": "hinam@neduet.edu.pk",
//             "phone": "03212161286",
//             "dob": null,
//             "address": "C-1. NED university Staff colony, Gulshan e Iqbal. Karachi,",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75270",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-08-26 22:56:30",
//             "updated_at": "2021-08-26 22:56:30",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 328,
//             "first_name": "Mehreen",
//             "last_name": "Salman",
//             "email": "mehreensalman2014@gmail.com",
//             "phone": "03343243800",
//             "dob": null,
//             "address": "Flat no B-305 Panama centre Sir shah Suleman road Gulshan-e-iqbal block 13-D3 karachi",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75300",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 0,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-08-31 06:16:20",
//             "updated_at": "2021-08-31 06:16:20",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         },
//         {
//             "id": 329,
//             "first_name": "Parvez",
//             "last_name": "Ahmad",
//             "email": "pz59pk@gmail.com",
//             "phone": "03340298146",
//             "dob": null,
//             "address": "B69 Hakeem Villas MainJinnahAvenue after Gate no 5 malir Cantt Karachi",
//             "country": "PK",
//             "city": "Karachi",
//             "postal": "75010",
//             "shipping_meta": null,
//             "billing_meta": null,
//             "user_type": "customer",
//             "brief": null,
//             "is_verified": 1,
//             "is_active": 1,
//             "is_pass_changed": 0,
//             "group_id": null,
//             "talentlms_id": null,
//             "image": null,
//             "created_at": "2021-09-06 17:03:48",
//             "updated_at": "2021-09-06 17:53:55",
//             "secret": null,
//             "provider": null,
//             "fb_token": null,
//             "deleted_at": null
//         }
//     ],
//     "first_page_url": "https://taazagosht.pk/api/get-users?page=1",
//     "from": 1,
//     "last_page": 8,
//     "last_page_url": "https://taazagosht.pk/api/get-users?page=8",
//     "next_page_url": "https://taazagosht.pk/api/get-users?page=2",
//     "path": "https://taazagosht.pk/api/get-users",
//     "per_page": 20,
//     "prev_page_url": null,
//     "to": 20,
//     "total": 160
// }