// {
//     "current_page": 1,
//     "data": [
//         {
//             "id": 46,
//             "title": "Car Care Products - Car Cleaning Products - Car Chemicals",
//             "slug": "home",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": 1,
//             "header_image": null,
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "show_meta": "on",
//                 "show_og": "on",
//                 "show_twitter": "on",
//                 "meta_title": "Car Care Products - Automotive Care - Car Cleaning Products | NASA Chemicals",
//                 "meta_keywords": "car chemicals,car care products,AUTOMOTIVE CHEMICALS,car wash chemicals,car cleaning chemicals,auto maintenance chemicals ,car cleaning products,Vehicle cleaning products,car chemical supplier,car chemical manufacturer,car chemical distributors",
//                 "meta_description": "Buy car care products online directly from the manufacturer at the best prices in Pakistan. We sell international quality car cleaning products, car care shampoo, glass cleaner, dashboard cleaner, brake oil, and all interior and exterior care.",
//                 "canonical": null,
//                 "og_title": "Automotive Care - Car Cleaning Products - Car Chemicals | NASA Chemicals",
//                 "og_url": "/",
//                 "og_type": null,
//                 "og_image": "/filemanager/photos/1/OG/64ec5eedd52c9.jpg",
//                 "og_description": "Find the best seller car care products online at the best prices in Pakistan. We are a manufacturer, a big distributor or supplier of International quality car cleaning products and automotive chemicals. We ensure the fastest delivery.",
//                 "twitter_title": "Automotive Care - Car Cleaning Products - Car Chemicals | NASA Chemicals",
//                 "twitter_url": "/",
//                 "twitter_card": null,
//                 "twitter_image": "/filemanager/photos/1/OG/64ec5eedd52c9.jpg",
//                 "twitter_description": "Find the best seller car care products online at the best prices in Pakistan. We are a manufacturer, a big distributor or supplier of International quality car cleaning products and automotive chemicals. We ensure the fastest delivery.",
//                 "scripts": null
//             },
//             "custom_css": ".welcome_image_area {\r\n    padding: 0 0 11px 0 !important;\r\n}",
//             "is_store": 1,
//             "created_at": "2019-10-30 04:06:41",
//             "updated_at": "2024-10-24 12:55:51"
//         },
//         {
//             "id": 47,
//             "title": "Shop",
//             "slug": "shop",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": 1,
//             "header_image": null,
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": null,
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": null,
//             "is_store": 1,
//             "created_at": "2019-11-04 23:57:38",
//             "updated_at": "2019-11-05 00:01:18"
//         },
//         {
//             "id": 48,
//             "title": "Blog",
//             "slug": "blog",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": null,
//             "header_image": "/filemanager/photos/1/5df47f9d3943c.jpg",
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "show_canonical": "on",
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": "https://nasachemicals.com/blog",
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": null,
//             "is_store": 0,
//             "created_at": "2019-11-12 01:46:42",
//             "updated_at": "2020-06-17 16:27:00"
//         },
//         {
//             "id": 49,
//             "title": "About Us",
//             "slug": "about-us",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": null,
//             "header_image": "/filemanager/photos/1/5e429dcd289e0.jpg",
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": null,
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": null,
//             "is_store": 0,
//             "created_at": "2019-11-12 03:43:22",
//             "updated_at": "2020-03-09 04:06:00"
//         },
//         {
//             "id": 50,
//             "title": "Contact Us",
//             "slug": "contact-us",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": null,
//             "header_image": "/filemanager/photos/1/5de1023789fb6.png",
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "show_canonical": "on",
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": "https://nasachemicals.com/contact-us",
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": null,
//             "is_store": 0,
//             "created_at": "2019-11-12 04:30:05",
//             "updated_at": "2020-07-17 13:01:54"
//         },
//         {
//             "id": 53,
//             "title": "Careers",
//             "slug": "careers",
//             "is_default": null,
//             "meta": null,
//             "is_home": 0,
//             "show_title": null,
//             "slider_id": null,
//             "header_image": "/filemanager/photos/1/5ed8e530bdefc.jpg",
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": null,
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": "h3 {\r\nmargin-bottom:20px;\r\n}\r\n.jobLs {\r\nborder: 1px solid #ddd;\r\nmax-width:50%;\r\nfont-size:17px;\r\n}\r\n.jobLs li {\r\ndisplay: flex;\r\nflex-direction: row;\r\njustify-content: space-between;\r\npadding:8px 20px;\r\nborder-bottom: 1px dashed #ddd;\r\nmargin-bottom: 3px;\r\n}\r\n.jobLs li span {\r\n\r\n}\r\n@media screen and (max-width:767px) {\r\n.jobLs {\r\nmax-width:100%;\r\n}\r\n.section p {\r\nmargin-bottom:18px;}\r\n }",
//             "is_store": 0,
//             "created_at": "2020-06-04 14:46:27",
//             "updated_at": "2021-04-17 13:26:30"
//         },
//         {
//             "id": 54,
//             "title": "Events",
//             "slug": "events",
//             "is_default": null,
//             "meta": null,
//             "is_home": 1,
//             "show_title": null,
//             "slider_id": null,
//             "header_image": "/filemanager/photos/1/gallery/6018ffe5f0c2a.jpg",
//             "meta_title": null,
//             "meta_desc": null,
//             "meta_keywords": null,
//             "seo": {
//                 "meta_title": null,
//                 "meta_keywords": null,
//                 "meta_description": null,
//                 "canonical": null,
//                 "og_title": null,
//                 "og_url": null,
//                 "og_type": null,
//                 "og_image": null,
//                 "og_description": null,
//                 "twitter_title": null,
//                 "twitter_url": null,
//                 "twitter_card": null,
//                 "twitter_image": null,
//                 "twitter_description": null,
//                 "scripts": null
//             },
//             "custom_css": null,
//             "is_store": 0,
//             "created_at": "2021-02-02 10:04:00",
//             "updated_at": "2024-10-24 12:55:51"
//         }
//     ],
//     "first_page_url": "https://nasachemicals.com/api/get-pages?page=1",
//     "from": 1,
//     "last_page": 1,
//     "last_page_url": "https://nasachemicals.com/api/get-pages?page=1",
//     "next_page_url": null,
//     "path": "https://nasachemicals.com/api/get-pages",
//     "per_page": 10,
//     "prev_page_url": null,
//     "to": 7,
//     "total": 7
// }