// {
//     "current_page": 1,
//     "data": [
//         {
//             "id": 6,
//             "user_id": null,
//             "category_id": 11,
//             "brand_id": null,
//             "title": "Antifreeze radiator coolant - Radiator Coolant Super",
//             "slug": "nasa-radiator-coolant-super",
//             "short_description": "NASA Radiator Anti-Freeze Coolant Super is an ethylene glycol-based OAT product that contains rust inhibitors, offering protection to the radiator from overheating, freezing, and rust. It safeguards engine blocks for all types of automobiles, diesel engines, and generators. This coolant is suitable for all metals, including aluminum radiators.",
//             "description": "<h2>Directions For Use Of Antifreeze Radiator Coolant:<br></h2><ul><li><span style=\"font-size: 18px;\">Ensure all radiator fittings and hoses are tight and in good\r\ncondition. Replace if necessary.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">If the radiator is dirty or rusty, use NASA Radiator Cleaner\r\nas directed.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Drain the radiator/cooling system and refill with clean\r\nwater. Run the engine for 5 minutes at normal speed, then turn off and drain\r\nthe water.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Fill the radiator with NASA Antifreeze Coolant; it is ready\r\nto use (no need to add water).</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">If the coolant level drops, refill only with NASA Antifreeze\r\nCoolant.</span><o:p></o:p></li></ul><h2>Warning Of Using Antifreeze Radiator Coolant:</h2><ul><li><span style=\"font-size: 18px;\">Contains Mono Ethylene Glycol. If swallowed, seek medical\r\nattention immediately.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Keep out of reach of children.</span><br></li></ul><p class=\"MsoNormal\"><o:p></o:p></p><h2>Packing Of Antifreeze Radiator Coolant:</h2><ul><li><span style=\"font-size: 18px;\">1 Litre</span></li><li><span style=\"font-size: 18px;\">3 Litres</span></li><li><span style=\"font-size: 18px;\">10 Litres</span></li><li><span style=\"font-size: 18px;\">20 Litres </span></li></ul>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c1c65315a.png",
//             "sku": null,
//             "price": 795,
//             "discounted_price": null,
//             "quantity": 1094,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fc14fb170c.png\",\"\\/filemanager\\/photos\\/746\\/667fc15c8de83.png\",\"\\/filemanager\\/photos\\/746\\/667fc15b0056d.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": "Car radiator water,Car radiator coolant,Engine coolant,Water coolant car radiator,radiator coolant price,radiator coolant pakistan,RADIATOR COOLANT SUPER",
//             "meta_description": "Buy radiator coolant for cars and protect your vehicles’ engine & generators from freezing, overheating, and rust. We are selling car radiator water online all over Pakistan with the fastest delivery system and at the most economical price.",
//             "meta_title": "Antifreeze Radiator Coolant - Anti freeze Chemical | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/nasa-radiator-coolant-super",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"27\",\"23\",\"20\",\"9\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "{\"1\":[\"6\",\"22\",\"18\",\"19\"],\"2\":[\"27\",\"28\",\"29\"]}",
//             "is_active": 1,
//             "created_at": "2019-11-28 07:18:16",
//             "updated_at": "2024-10-08 09:27:10"
//         },
//         {
//             "id": 7,
//             "user_id": null,
//             "category_id": 7,
//             "brand_id": null,
//             "title": "BATTERY MIXTURE - Car Battery Solution (20Ltr)",
//             "slug": "nasa-battery-mixture-20ltr",
//             "short_description": "NASA Battery Mixture is a high-purity sulfuric acid solution designed for use in automotive and industrial lead-acid batteries. This specially formulated mixture maintains optimal specific gravity, which helps protect battery plates from premature degradation and enhances overall battery performance.",
//             "description": "<h2>Advantages of&nbsp;Battery Mixture:&nbsp;</h2><ul><li><span style=\"\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Protects against premature decomposition of battery plates.</span><o:p></o:p></span></li><li><span style=\"font-family:\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Improves performance and charging efficiency, especially for batteries\r\nshowing signs of weakness.</span></span></li><li><span style=\"\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Compatible with all types of lead-acid batteries, including those used\r\nin cars, trucks, UPS systems, and power generators.</span><b><o:p></o:p></b></span></li></ul><h3><br></h3><h2>Directions for Use of Battery Mixture:</h2><ul><li><span style=\"\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Disconnect the battery from the vehicle or equipment.</span><o:p></o:p></span></li><li><span style=\"font-family:\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Carefully remove any old mixture or water from the battery cells.</span><o:p></o:p></span></li><li><span style=\"font-family:\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Fill each cell with NASA Battery Mixture.</span><o:p></o:p></span></li><li><span style=\"font-size: 18px;\" sans-serif\";=\"\" font-weight:=\"\" normal;=\"\" font-size:=\"\" 18px;\"=\"\">Charge the battery using a suitable charger according to the\r\nmanufacturer's instructions.</span></li><li><span style=\"\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\">Reinstall the battery in the vehicle or equipment.</span></span></li></ul><p><strong><span style=\"font-family:\" calibri\",\"sans-serif\";=\"\" mso-ascii-theme-font:minor-latin;mso-fareast-font-family:\"times=\"\" new=\"\" roman\";=\"\" mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;font-weight:=\"\" normal\"=\"\"><span style=\"font-size: 18px;\"><br></span></span></strong></p><h2>Precautions for Use of Battery Mixture:</h2><ul><li><span style=\"color: rgb(0, 0, 0); font-size: 14px;\"><span style=\"font-size: 18px;\" sans-serif\";=\"\" font-weight:=\"\" normal;=\"\" font-size:=\"\" 18px;\"=\"\">This product is corrosive. Handle with care and follow all safety instructions.</span></span></li><li><span style=\"color: rgb(0, 0, 0); font-size: 14px;\"><span style=\"font-size: 18px;\" sans-serif\";=\"\" font-weight:=\"\" normal;=\"\" font-size:=\"\" 18px;\"=\"\">Do not apply to hot surfaces or mix with other chemicals.</span></span></li><li><span style=\"color: rgb(0, 0, 0); font-size: 14px;\"><span style=\"font-size: 18px;\" sans-serif\";=\"\" font-weight:=\"\" normal;=\"\" font-size:=\"\" 18px;\"=\"\">Avoid contact with metals, as the mixture reacts with most metals and\r\nmay produce flammable hydrogen gas.</span></span></li></ul><h2>Pack Size of Battery Mixture:</h2><p><span style=\"font-size: 18px;\">20 Ltr can</span></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/66e2991061714.png",
//             "sku": null,
//             "price": 10400,
//             "discounted_price": null,
//             "quantity": 988,
//             "gallery": "null",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": null,
//             "meta_description": "Buy car battery mixture - We are a manufacturer and distributor of battery mixture (20 LTR) in Pakistan available at a large quantity. We have all International quality products for the best delivery.",
//             "meta_title": "Car Battery Mixture - Battery Solution Mixture | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-battery-mixture-20ltr",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"19\",\"18\",\"15\",\"9\",\"6\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 08:30:44",
//             "updated_at": "2024-09-14 12:53:39"
//         },
//         {
//             "id": 11,
//             "user_id": null,
//             "category_id": 9,
//             "brand_id": null,
//             "title": "Automatic Transmission Fluid - Transmission Oil (1 LTR)",
//             "slug": "nasa-atf-diii-1ltr",
//             "short_description": "NASA Automatic Transmission Fluid Dexron III is made up of highly refined synthetic base oil utilizing VHVI technology. This provides excellent performance in automatic gears, power steering, and other related applications. Our top-quality transmission fluid offers superior lubrication to all your components, enhancing car performance and ensuring a smooth and hassle-free driving experience. NASA ATF DEXRON III cleans dirt from metal surfaces, conditions gaskets, and improves temperature range and rotational speed.",
//             "description": "<h2>Properties of Automatic Transmission Fluid:<br></h2><ul><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Contains high-quality additives for VI improvers,\r\nantirust, antiwear, antioxidant, and antifoam properties.</span><o:p></o:p></li><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Balanced viscosity for all weather conditions.</span><o:p></o:p></li><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Ensures complete compatibility with most synthetic rubber\r\nsealers.</span><o:p></o:p></li></ul><h2>Specifications of Automatic Transmission Fluid:</h2><ul><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Meets GM Dexron and Ford Mercon specifications.</span><o:p></o:p></li><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Meets Detroit Diesel Allison and Caterpillar\r\nspecifications.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Meets ATF III specifications of most automobile\r\nmanufacturers.</span><br></li></ul><p class=\"MsoNormal\" style=\"mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;\r\nline-height:normal\"><o:p></o:p></p><h2>Precautions of Automatic Transmission Fluid:</h2><ul><li><span style=\"font-size: 18px;\">Avoid contact with eyes, skin, and clothing. Wash\r\nthoroughly in case of contact.</span></li><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">If swallowed, do not induce vomiting. Give water and\r\nimmediately see a doctor.</span><o:p></o:p></li><li style=\"line-height: normal;\"><span style=\"font-size: 18px;\">Keep out of reach of children.</span></li></ul><p><br></p><h3> Packing of Automatic Transmission Fluid:</h3><p>1 Litre</p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c713e136d.png",
//             "sku": null,
//             "price": 1035,
//             "discounted_price": null,
//             "quantity": 924,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fc063a00be.png\",\"\\/filemanager\\/photos\\/746\\/667fc0651409d.png\",\"\\/filemanager\\/photos\\/746\\/667fc063e37e0.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": "ATF DEXRON III,Automatic Transmission Fluid",
//             "meta_description": "Buy transmission fluid online ATF DEXRON III that contains high-quality additives for VI improvers, Antirust, antiwear, antioxidant and antifoam properties. It provides excellent performance in Automatic Gears, Power Steering and other related application",
//             "meta_title": "Automatic Transmission Fluid - ATF DEXRON III | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/nasa-atf-diii-1ltr",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"14\",\"13\",\"12\",\"10\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 09:23:51",
//             "updated_at": "2024-09-12 12:36:29"
//         },
//         {
//             "id": 12,
//             "user_id": null,
//             "category_id": 9,
//             "brand_id": null,
//             "title": "POWER STEERING FLUID - Steering Oil (350ml)",
//             "slug": "nasa-power-steering-fluid-354ml",
//             "short_description": "NASA Power Steering Fluid is designed to protect and lubricate seals, prevent wear, oxidation, and foaming, as well as guard against leaks and breakdown. It can also serve as a hydraulic fluid for machinery operated hydraulically. Our power steering fluid is refined from quality minerals that ensures high performance. The fluid is manufactured to fulfill the operational needs of your steering system. The product is designed to take the best care of your power steering system and to enable it to deliver smooth performance.",
//             "description": "<h2>Direction Of Power Steering Oil:</h2><p><span style=\"font-size: 18px;\">With Engine off add power steering fluid in a reservoir as needed.</span></p><h2>Caution Of Power Steering Oil:</h2><p><span style=\"font-size: 18px;\">Avoid skin and eye contact as it may cause eye irritation. as first aid, flush eyes with water, for skin flush with water and soap and contact with a physician if irritation persists. keep out of reach of children.</span></p><h2>Packing Of Power Steering Oil:</h2><p><span style=\"font-size: 18px;\">350 ml ,</span></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c2bdc7930.png",
//             "sku": null,
//             "price": 580,
//             "discounted_price": null,
//             "quantity": 941,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbfd72e9f6.png\",\"\\/filemanager\\/photos\\/746\\/667fbfd742836.png\",\"\\/filemanager\\/photos\\/746\\/667fbfd7cc72c.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": "POWER STEERING FLUID,power steering fluid pakistan,power steering fluid price in pakistan,steering oil,power steering oil online",
//             "meta_description": "Find high-quality steering fluid online at the most economical price in Pakistan to enhance smooth driving experience. Give yourself ease in turning your car with power steering fluid.",
//             "meta_title": "Steering Oil - Power Steering Fluid | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-power-steering-fluid-354ml",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"14\",\"13\",\"11\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 09:35:56",
//             "updated_at": "2024-10-03 13:11:17"
//         },
//         {
//             "id": 13,
//             "user_id": null,
//             "category_id": 9,
//             "brand_id": null,
//             "title": "Car GEAR OIL - Gearbox Oil 80W/90 (1Ltr)",
//             "slug": "nasa-gear-oil-80w90-1ltr",
//             "short_description": "NASA Gear Oil GL-5 80W/90 is a high-quality automotive gear oil that provides outstanding performance in most gear applications. Applicable where GL-5 is recommended, NASA Gear Oil meets the needs of service conditions ranging from mild to severe. Tailored for use in manual gearboxes, transmissions, and transaxles, it ensures smooth operation and protects your vehicle's gear system from damage.",
//             "description": "<h2>General Characteristics of Gear Oil GL-5:</h2><ul><li><span style=\"font-size: 18px;\">Meets API service category GL-5.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Compatible with specifications of major automobile\r\nmanufacturers.</span></li></ul><h2>Uses and Benefits of Gear Oil GL-5:</h2><ul><li><span style=\"font-size: 18px;\">Ensures smooth transmission performance.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Protects important gear system components from damage.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Prevents scuffing and scouring of vital components.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Reduces repair costs by providing sufficient lubrication.</span><br></li></ul><p class=\"MsoNormal\"><o:p></o:p></p><h2>Precautions of Using Gear Oil:</h2><ul><li><span style=\"font-size: 18px;\">Avoid contact with eyes, skin, and clothing. Wash thoroughly\r\nin case of contact.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">If swallowed, do not induce vomiting. Give water and seek\r\nimmediate medical attention.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Store in a cool, dry place away from heat and flames.</span></li><li><span style=\"font-size: 18px;\">Keep out of reach of children.</span><o:p></o:p></li></ul><p class=\"MsoNormal\"><o:p></o:p></p><h2>Packing of Gear Oil GL-5: </h2><p><span style=\"font-size: 18px;\">1 Litre</span><br></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c36fa4c18.png",
//             "sku": null,
//             "price": 1155,
//             "discounted_price": null,
//             "quantity": 959,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbf3fbf404.png\",\"\\/filemanager\\/photos\\/746\\/667fbf3de61a7.png\",\"\\/filemanager\\/photos\\/746\\/667fbf3f844c1.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": null,
//             "meta_description": "Shop now car gear oil to protect gears teeth from corrosion. We are providing gear oil 80w/90 in Pakistan at economical prices. Car gear oil speeds up performance, protects the gearbox and lengthens vehicles working life.",
//             "meta_title": "Gear Oil - Car Gear Oil | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-gear-oil-80w90-1ltr",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"14\",\"12\",\"11\",\"10\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 09:43:16",
//             "updated_at": "2024-09-12 10:28:27"
//         },
//         {
//             "id": 14,
//             "user_id": null,
//             "category_id": 9,
//             "brand_id": null,
//             "title": "Brake Oil - Car Brake Fluid",
//             "slug": "nasa-brake-fluid-355ml",
//             "short_description": "NASA Brake Fluid Dot-3 is a mixture of Poly Glycol Ethers with special additives designed to ensure reliable and consistent braking performance. It meets international standards FMVSS NO 116 DOT 3, JIS K2233, and SAE J1703. This fluid maintains stability in viscosity and heat resistance under high temperatures, providing protection against brake failure. Its advanced formula can absorb moisture and prevent rust, ensuring the longevity and effectiveness of your braking system.",
//             "description": "<h2>Benefits of Car Brake Fluid:</h2><ul><li><span style=\"font-size: 18px;\">Maintains stability in viscosity and heat resistance under\r\nhigh temperatures.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Protects against brake failure.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Absorbs moisture and prevents rust.</span></li><li><span style=\"font-size: 18px;\">Compatible with other DOT 3 fluids.</span><br></li></ul><p class=\"MsoNormal\"><o:p></o:p></p><h2>Directions for Use Of Brake Fluid Dot-3:</h2><ul><li><span style=\"font-size: 18px;\">Keep the brake fluid bottle clean and dry, free from dust\r\nand other contaminants.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Open the Brake Fluid Reservoir and fill the fluid.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">After filling, release all entrapped air from the brake\r\nsystem.</span><br></li></ul><p class=\"MsoNormal\"><o:p></o:p></p><h2>Precautions of Brake Fluid Dot-3:</h2><ul><li><span style=\"font-size: 18px;\">Contains a mixture of Poly Glycol Ethers.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Avoid spilling brake fluid on brake linings and car paint.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">It is a Poisonous liquid; do not drink.</span></li><li><span style=\"font-size: 18px;\">Keep out of reach of children.</span></li></ul><h2>Packing of Brake Fluid Dot-3: </h2><ul><li><span style=\"font-size: 18px;\">355 mL</span></li><li><span style=\"font-size: 18px;\">1 Litre</span></li></ul>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c2cde774f.png",
//             "sku": null,
//             "price": 510,
//             "discounted_price": null,
//             "quantity": 17,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\",\"4\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbeb81edbb.png\",\"\\/filemanager\\/photos\\/746\\/667fbeb7b2836.png\",\"\\/filemanager\\/photos\\/746\\/667fbec734554.png\",\"\\/filemanager\\/photos\\/746\\/667fbec6e2a9f.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": null,
//             "meta_description": "Get genuine quality brake oil online at the most economical prices to make your car able to stop at a kiss of the brake pedal. Car brake oil smoothly runs various components of the braking system and keeps it efficient.",
//             "meta_title": "Car Brake Oil - Brake Fluid | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-brake-fluid-355ml",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"13\",\"12\",\"11\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "{\"1\":[\"6\",\"21\"]}",
//             "is_active": 1,
//             "created_at": "2019-11-28 09:49:36",
//             "updated_at": "2024-09-12 10:27:29"
//         },
//         {
//             "id": 16,
//             "user_id": null,
//             "category_id": 8,
//             "brand_id": null,
//             "title": "BRAKE CLEANER - car brake cleaning spray (450ml)",
//             "slug": "nasa-brake-cleaner-450ml",
//             "short_description": "NASA Brake Cleaner is a high-power formulation designed to clean brake linings, cylinders, drum parts, springs, rotors, caliper units, pads, and other areas of the braking mechanism, with or without disassembly. This cleaner effectively dissolves the hardest grit and grime, ensuring your brakes are completely clean for optimal performance.",
//             "description": "<h2>Directions for Use of Brake Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Shake well before use.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Insert the extension tube.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Hold the can upright 6”-8” from the surface.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Use short bursts until brake parts are amply wet.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Continue as necessary to allow contaminants to run off.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Air dry or wipe off with a clean cloth.</span></li><li><span style=\"font-size: 18px;\">Protect all rubber, plastic, and painted surfaces from\r\naccidental overspray.</span><o:p></o:p></li></ul><h2>Precautions of Using Brake Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Accidental over spray should be washed off immediately. </span></li><li><span style=\"font-size: 18px;\">Contents are highly flammable and under pressure.</span></li><li><span style=\"font-size: 18px;\">Keep away from heat and flame.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Do not puncture or incinerate the can.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Store in a well-ventilated place, away from sunlight and\r\ntemperatures exceeding 35°C.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Causes skin irritation; may cause drowsiness or dizziness.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Keep the container tightly closed and store locked up.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Keep away from children.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Consider covering areas of the car that could be exposed to\r\nthe brake cleaner before application.</span><o:p></o:p></li></ul><h2>Packing of Brake Cleaner: </h2><p><span style=\"font-size: 18px;\">450 mL</span></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c3101a1b1.png",
//             "sku": null,
//             "price": 635,
//             "discounted_price": null,
//             "quantity": 590,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbdffe187a.png\",\"\\/filemanager\\/photos\\/746\\/667fbdfeaecf0.png\",\"\\/filemanager\\/photos\\/746\\/667fbdff7607a.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": null,
//             "meta_description": "Buy car brake cleaning spray. This brake cleaner cleans lining, cylinders, drum parts, springs, and other parts of the brake. The brake cleaner spray bottle is offered at the most economical prices in Pakistan.",
//             "meta_title": "Brake Cleaner Spray - Brake Parts Cleaner Spray | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-brake-cleaner-4500ml",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"22\",\"21\",\"17\",\"15\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 10:00:31",
//             "updated_at": "2024-09-25 01:43:19"
//         },
//         {
//             "id": 17,
//             "user_id": null,
//             "category_id": 8,
//             "brand_id": null,
//             "title": "CONTACT CLEANER spray - electronic items cleaner",
//             "slug": "nasa-contact-cleaner",
//             "short_description": "NASA Contact Cleaner is a versatile fluid designed to clean oil, carbon, dust, grease, and dirt from sensitive electronic components, circuit boards, control switches, electronic panels, contact relays, and generators.",
//             "description": "<h2>Additional Information:</h2><p><span style=\"font-size: 18px;\">This contact cleaner spray quickly dries, leaving no residue on electronic components. It is ideal for use on batteries, terminals, and electric panels. The formulation ensures thorough cleaning of Grime while maintaining safety and efficiency.</span></p><h2>Directions for Use of Contact Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Use an extension tube, if required.</span></li><li><span style=\"font-size: 18px;\">Shake well before use.</span></li></ul><h2>Precautions of Using Contact Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Contents are highly flammable and under pressure.</span></li><li><span style=\"font-size: 18px;\">Keep away from heat and flame.</span></li><li><span style=\"font-size: 18px;\">Do not puncture or incinerate the can.</span></li><li><span style=\"font-size: 18px;\">Use at room temperature.</span></li><li><span style=\"font-size: 18px;\">Keep out of reach of children.</span></li></ul><h2>Packing of Contact Cleaner:</h2><p><span style=\"font-size: 18px;\">200 mL</span><br></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c2c9070fc.png",
//             "sku": null,
//             "price": 465,
//             "discounted_price": null,
//             "quantity": 187,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbd7f62720.png\",\"\\/filemanager\\/photos\\/746\\/667fbd815e493.png\",\"\\/filemanager\\/photos\\/746\\/667fbd7f61c00.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": null,
//             "meta_description": "Shop multi purpose contact cleaner solution that cleans oil dirt, grease, dust, circuit board, electronic panel, generators, etc. We are offering the best contact cleaner spray in Pakistan at the best prices.",
//             "meta_title": "Contact Cleaner Spray - Oil Cleaner Spray | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/nasa-contact-cleaner",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"21\",\"16\",\"15\",\"5\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 10:06:31",
//             "updated_at": "2024-10-18 22:20:26"
//         },
//         {
//             "id": 18,
//             "user_id": null,
//             "category_id": 7,
//             "brand_id": null,
//             "title": "Glass Cleaner - Car and Home Glass Cleaner Spray - Tiles Cleaner",
//             "slug": "nasa-glass-cleaner",
//             "short_description": "NASA Glass Cleaner cleans a wide range of glassware including window panes, auto windshields, TV screens, tiles, mirrors, and various household items. This improved formula includes a special anti-static agent, providing a streak-free shine on both indoor and outdoor glass surfaces. It effectively removes grime, dirt, and soil, maintaining the original shine of the glass.",
//             "description": "<h2>Uses and Benefits of Glass Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Provides a streak-free shine with an anti-static formula.</span></li><li><span style=\"font-size: 18px;\">Suitable for maintaining the original shine of glass\r\nsurfaces.</span><o:p></o:p></li></ul><h2>Directions for Use of Glass Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Uncover the tab.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Spray NASA Glass Cleaner on the glass surface.</span></li><li><span style=\"font-size: 18px;\">Wipe off with a cloth or paper towel.</span><o:p></o:p></li></ul><h2>Application of Glass Cleaner:</h2><ul><li><span style=\"font-size: 18px;\">Window Panes.</span></li><li><span style=\"font-size: 18px;\">Auto Windshields.</span></li><li><span style=\"font-size: 18px;\">TV Screens.</span></li><li><span style=\"font-size: 18px;\">Tiles.</span></li><li><span style=\"font-size: 18px;\">Mirrors.</span></li><li><span style=\"font-size: 18px;\">Various other household items.</span></li></ul><h2>Packing of Glass Cleaner:</h2><p><span style=\"font-size: 18px;\">500 mL</span></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635c26122f58.png",
//             "sku": null,
//             "price": 620,
//             "discounted_price": null,
//             "quantity": 888,
//             "gallery": "{\"sort_order\":[\"0\",\"0\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbd2a3da30.png\",\"\\/filemanager\\/photos\\/746\\/667fbd2a63d57.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": "GLASS CLEANER,glass cleaner spray,glass cleaner liquid,glass cleaner in pakistan,glass cleaner price in pakistan,car glass cleaner,home glass cleaner,window glass cleaner,mirror cleaner spray,tiles cleaner spray",
//             "meta_description": "Find the best glass cleaner spray online at the lowest prices in Pakistan. This glass cleaner liquid has excellent usages that clean and shines car glass, windows, mirrors, tiles, and the like.",
//             "meta_title": "Glass cleaner - Car & Home glass cleaner spray | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-glass-cleaner",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "null",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 10:13:29",
//             "updated_at": "2024-09-12 10:03:19"
//         },
//         {
//             "id": 19,
//             "user_id": null,
//             "category_id": 7,
//             "brand_id": null,
//             "title": "CAR SHAMPOO - Car Wash Shampoo",
//             "slug": "nasa-car-shampoo",
//             "short_description": "NASA Car Shampoo is formulated with wax and can be safely used on all hard washable surfaces including car bodies, glass, plastic, steel, ceramic, and leather. It effectively cleans dirt, leaving surfaces shiny and fragrant, while also providing a deep shine after cleaning.",
//             "description": "<h2>Directions for Use of Car Shampoo:</h2><p><ul></ul>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<ul></ul></p><ul><li><span style=\"font-size: 18px;\">Shake well before use.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Clean the dirt on the car with tap water.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Fill 2 caps (or as required) of NASA Car Shampoo into a\r\nquarter bucket of water.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Mix well to ensure the shampoo is evenly distributed in the\r\nwater.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Soak a microfiber cloth or sponge in the solution and gently mop\r\nit onto the surface.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Wash off with clean water to remove dirt and shampoo\r\nresidue.</span><o:p></o:p></li></ul><h2>Precautions of Using Car Shampoo:</h2><ul><li><span style=\"font-size: 18px;\">Rinse and dry hands after use to avoid any skin irritation.</span><o:p></o:p></li><li><span style=\"font-size: 18px;\">Individuals with sensitive or damaged skin should avoid\r\nprolonged contact with the product.</span></li><li><span style=\"font-size: 18px;\">Keep out of reach of children.</span><o:p></o:p></li></ul><h2>Packing of Car Shampoo: </h2><p><span style=\"font-size: 18px;\">500 mL</span><br></p>",
//             "image": "https://www.nasachemicals.com/filemanager/photos/746/6635be902046c.png",
//             "sku": null,
//             "price": 620,
//             "discounted_price": null,
//             "quantity": 633,
//             "gallery": "{\"sort_order\":[\"1\",\"2\",\"3\"],\"image\":[\"\\/filemanager\\/photos\\/746\\/667fbce05c894.png\",\"\\/filemanager\\/photos\\/746\\/667fbce1e9f5c.png\",\"\\/filemanager\\/photos\\/746\\/667fbce311c8b.png\"]}",
//             "discount": null,
//             "post_type": 1,
//             "meta_keywords": "CAR SHAMPOO,car shampoo in pakistan,car wash shampoo,car shampoo price,car shampoo price in pakistan,car cleaning shampoo",
//             "meta_description": "Discover the best seller car shampoo online with the best economical price in Pakistan that anyone can afford. Your car depicts your personality so keep it clean from every corner.",
//             "meta_title": "Car Shampoo - Car Cleaning Shampoo | NASA Chemicals",
//             "link_canonical": "https://nasachemicals.com/product/nasa-car-shampoo",
//             "is_featured": 1,
//             "additional": "{\"what's_new?\":null}",
//             "related": "[\"18\",\"15\",\"9\",\"8\",\"7\",\"6\"]",
//             "best_seller": 0,
//             "top_rated": 0,
//             "unit": null,
//             "weight": 0,
//             "variations": "null",
//             "is_active": 1,
//             "created_at": "2019-11-28 10:20:01",
//             "updated_at": "2024-10-16 15:44:56"
//         }
//     ],
//     "first_page_url": "https://www.nasachemicals.com/api/get-products?page=1",
//     "from": 1,
//     "last_page": 3,
//     "last_page_url": "https://www.nasachemicals.com/api/get-products?page=3",
//     "next_page_url": "https://www.nasachemicals.com/api/get-products?page=2",
//     "path": "https://www.nasachemicals.com/api/get-products",
//     "per_page": 10,
//     "prev_page_url": null,
//     "to": 10,
//     "total": 25
// }